config/routes.rb
Rails.application.routes.draw do
  root to: 'statics_page#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create

    @comment = Comment.new
    @comment.post_id = params[:comment][:post_id]
    @comment.user_id = current_user.id
    @comment.content = params[:comment][:content]

    if @comment.save
      flash[:success] = 'Comment successfully'
      respond_to do |format|
        format.js
      end

    else
      @post = @comment.post
      render 'posts/show'
    end
  end

  def destroy

    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to post_path(@comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit :content, :post_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.paginate(page: params[:page], per_page: 2)

  end

  def show
    @post = Post.find_by(params[:id])
    @comment = Comment.new
  end

  def new

    @post = Post.new

    # params[:tags] # 'Java PHP OOP'
    # tags = params[:tags].split(' ') # ['Java', 'PHP', 'OOP']
    #
    # tags.each do |tag_name|
    #   @post.tags.new name: tag_name
    # end
    #
    # if @post.save
    # else
    # end
  end

  def create
    @post = Post.new
    @post.user_id = current_user.id
    @post.title = params[:post][:title]
    @post.content = params[:post][:content]
    if @post.save
      flash[:success] = 'Create post successfully'
      redirect_to posts_path
    else
      flash[:danger] = 'Create post failly'
    end
  # 'Java PHP OOP'
    tags = params[:post][:tags].split(' ') # ['Java', 'PHP', 'OOP']
    tags.each do |tag_name|
    @post.tags.new name: tag_name
    end
    if @post.save
      flash[:success] = "add tag name successfully"
  
    else
      flash[:alert] = "add tag name failly"
    end
  end
end

app/controllers/statics_page_controller.rb
class StaticsPageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/statics_page_helper.rb
module StaticsPageHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
var str = '<h3><%= @comment.user.email %></h3><ul><li><%= @comment.content %></li></ul><%= link_to('Delete', comment_path(@comment), method: :delete, class: 'btn btn-outline-primary' ) %>'

var temp = document.createElement('div');
temp.innerHTML = str;

document.getElementById('comments').prepend(temp);

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in?%>
      <li>
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/"><%= current_user.email%> <span class="sr-only">(current)</span></a>
      </li>
      <%= link_to 'Logout', destroy_user_session_path, class: 'nav-link', method: :delete,data: {confirm: 'Are you sure?'} %>
        </li>
        <% else %>
        <li class="nav-item active">
          <a class="nav-link" href="http://localhost:3000/">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class='nav-item'>
            <%= link_to 'Login', new_user_session_path, class: 'nav-link'  %>
        </li>
        <li class='nav-item'>
            <%= link_to 'sign up', new_user_registration_path,class: 'nav-link'  %>
        </li>
      <% end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav'%>
    <main role= 'main'>
      <%= render 'layouts/flash'%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<%= link_to post_path(post) do %>
    <div class="media">
      <img class="mr-3" src="http://data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2264%22%20height%3D%2264%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2064%2064%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1683d649a6b%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A10pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1683d649a6b%22%3E%3Crect%20width%3D%2264%22%20height%3D%2264%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.5546875%22%20y%3D%2236.5%22%3E64x64%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" alt="Generic placeholder image">
      <div class="media-body">
        <h5 class="mt-0"><%= post.user.email %></h5>
        <p><%= post.content %></p>
      </div>
    </div>
    <% end %>
<% end %>
 <button><a href = "/posts/new">Create post</a></button> 
<!-- <%= link_to 'create post', url: '/posts/new',class: 'btn btn-primary'%> -->
<%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>

app/views/posts/new.html.erb
<div class='col col-sm-6 col-md-6 col-lg-4 col-xl-3'>
   <h1>Create post</h1>
   <%= form_for @post, url: posts_path do |f| %>
     <div class='form-group'>
       <%= f.label :title %>
       </br>
       <%= f.text_field :title, class: 'form-control' %>
     </div>
     <div class='form-group'>
       <%= f.label :content %>
       </br>
       <%= f.text_area :content, class: 'form-control' %>
     </div>
     <div class='form-group'>
       <%= f.label :tags %>
       </br>
       <%= f.text_field :tags, class: 'form-control', value: '' %>
     </div>
     </br>
     <%= f.submit 'Create post', class: 'btn btn-primary' %>
   <% end %>
 </div>
</div>

app/views/posts/show.html.erb
<h1> welcom to my post: <%= @post.content %></h1>

<div class="media">
  <img class="mr-3" src="http://data:image/svg+xml;charset=UTF-8" alt="Generic placeholder image">
  <div class="media-body">
    <h5 class="mt-0"><%= @post.user.email %></h5>
    <p><%= @post.title %></p>
    <p><%= @post.content %></p>
  </div>
</div>

<%= form_for @comment, remote: true do |f| %>
  <%= f.hidden_field :post_id, value: @post.id %>
  <div class='form-group'>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  <%= f.submit 'Comment', class: 'btn btn-primary' %>
<% end %>

<div id = "comments">
<% @post.comments.each do |comment| %>
  <div class='comment'>
    <div class="media">
    <div class="media-body">
      <h3><%=comment.user.email%></h3>
      <p><%= comment.content%></p>
      <% if comment.user.id == current_user.id %>
       <%= link_to('Delete', comment_path(comment), method: :delete, class: 'btn btn-outline-primary' ) %>
     <% end %>
    </div>
  </div>
</div>

<% end %>
</div>

app/views/statics_page/home.html.erb
<main role="main" class="container">

  <div class="starter-template">
    <h1>Bootstrap starter template</h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
  </div>

</main>